### ISSUE TITLE
Tabular Editor 3 Support?

### ISSUE THREAD

**Issue by AGSSAS** [m-kovalsky/MiniModelBuilder#4]
I really like the Mini Model builder (used with TE2) but get script errors when attempting to use this in Tabular Editor 3.  Is there any Tabular Editor 3 support for this currently, and if not is any planned?  Thanks.

**Comment by m-kovalsky** [comment]
I filed this bug in TE3.  https://github.com/TabularEditor/TabularEditor3/issues/539

This can also be solved by changing the first few lines of the script to this. Note that the Mini Model Builder runs sub-optimally within TE3 due to scaling issues. Will have to investigate it.

#r "System.Drawing"
#r "System.Xml"

using System.Drawing;
using System.Xml;

**Comment by AGSSAS** [comment]
Ah, this is great, thanks.  I just wanted to be sure I wouldn't have to change my workflow in order to upgrade to TE3.  The mini model builder is a really great way to focus on who can access what data without duplicating measures across models, thanks for creating this!
